### ISSUE TITLE
can not open `C Programming/Structure and Style`

### ISSUE THREAD

**Issue by zhuzaifangxuele** [SalGnt/cscs#34]
hi, i can not open the link `http://ieng9.ucsd.edu/~cs30x/indhill-cstyle.html`.  is something wrong?
![image](https://user-images.githubusercontent.com/52022596/105357211-66339c80-5bec-11eb-8b25-ceb26c5f93b5.png)
`

**Comment by SalGnt** [comment]
Apparently the resource is not available anymore.
